### ISSUE TITLE
This repo is empty

### ISSUE THREAD

**Issue by blim2** [hbouchard2/trial_run#1]
wai is this empt?

**Comment by blim2** [comment]
helo, is hotdog a sandwich?

**Comment by hbouchard2** [comment]
I wanted to make sure I wasn't committing to master if I created a new one 😞

**Comment by blim2** [comment]
yes, but how much water do I add when boiling pasta?

**Comment by hbouchard2** [comment]
enough so that the pot boils over

**Comment by blim2** [comment]
wow! thank you so much! have a nice day :)
